### PR TITLE
COMPLETE revamp of events service

### PR DESCRIPTION
**Pull request by AydanPirani**
- Added mongoose + typegoose
- Prototyped error handler (it's working!!! @akulsharma1  @Timothy-Gonzalez )
- Redesigned events service
- Added staff service

### CODE REVIEW

**Comment by lasyaneti** [comment]
preview broken with internal error 😭

**Comment by lasyaneti** [comment]
testing to do 

### /event/
- [x] `GET`, return only public-facing events (no isPrivate or isStaff) 
- [x] `POST`, ensure events are being created in the right collections, also if `isStaff` -> has no `isPrivate` field
- [x] `POST`/`PUT`, admin auth only 
- [x] `POST`/`PUT` test aydans public vs staff event type logic   
- [x] `POST`/`PUT` test start time <= end time

### /event/:EVENTID
- [x] `GET` staff only can get staff events 
- [x] `GET` everyone can get public events 
- [x] `DELETE` admin only can delete any sort of event

### /event/staff/
- [x] `GET` staff only can get staff events 

/event/expiration
- [x] `GET` staff only  
- [ ] `PUT` admin only, exp must be after start time, default must be end time

**Comment by AydanPirani** [comment]
Note that expiration is now metadata

**Comment by AydanPirani** [comment]
Results of my tests

- [x] GET, return only public-facing events (no isPrivate or isStaff)
- [x] POST, ensure events are being created in the right collections, also if isStaff -> has no isPrivate field
- [x] POST/PUT, admin auth only
- [x] POST/PUT test aydans public vs staff event type logic
- [x] POST/PUT test start time <= end time
- [x] GET staff only can get staff events
- [x] GET everyone can get public events
- [x] DELETE admin only can delete any sort of event
- [x] GET staff only can get staff events
- [x] GET staff only
- [x] PUT admin only, exp must be after start time, default must be end time

**Review by lasyaneti — APPROVED** [review]

**Pull request merged**
