### PR TITLE
Remove `DatabaseHelper` in favor of `MongoClient`

### LINKED ISSUE #35: Rework database abstraction logic
A couple of problems with this implementation:

- https://github.com/HackIllinois/adonix/blob/a25b72fc61cfda49cc9f0578757b6ed9aa788d35/src/database.ts#L28-L34
This line spawns a new connection with the database. Given the current configuration, when a lambda function is invoked, it loads up the designated service (cold start) calls the appropriate route, and spawns a new database. If the lambda instance is still running when another request is made to a route said lambda handles, then spawns a new database connection rather than using the existing one. This is most likely the reason why you are hitting Mongo's connection limit.

- https://github.com/HackIllinois/adonix/blob/a25b72fc61cfda49cc9f0578757b6ed9aa788d35/src/database.ts#L6
`DatabaseHelper` as an abstract class does not seem to be the appropriate tool for the job imo. Something like `namespace` can simplify the meaning behind what `DatabaseHelper` intends to be.

- https://github.com/HackIllinois/adonix/blob/a25b72fc61cfda49cc9f0578757b6ed9aa788d35/src/database.ts#L15-L16
The act of searching up a database in a lookup table is sort of redundant and negligent in performance gain if we are gonna pass in the database name anyway.

- `DatabaseHelper.getCollection(databaseName, collectionName)` is now more restrictive for no particularly good reason (as `client.db(databaseName).collection(collectionName)` achieves the same thing while still having full control over `client`)

So, it makes more sense to scrap `DatabaseHelper` in favor of using `client` directly. More here: https://www.mongodb.com/docs/atlas/manage-connections-aws-lambda/

Example of a possible `database.ts`:
```ts
import "dotenv";
import { MongoClient } from "mongodb";

const username = process.env.DB_USERNAME;
const password = process.env.DB_PASSWORD;
const server = process.env.DB_SERVER;

const credInfo = (username) ? `${encodeURIComponent(username)}:${encodeURIComponent(password || "")}@` : "";
if (!server) {
	throw new Error("server URI not provided in .env file!");
}

const uri = `mongodb+srv://${credInfo}${server}`;

const client = new MongoClient(uri, {
	retryWrites: true,
	w: "majority",
});

export default client;
```

Functions that then use `DatabaseHelper` can be refactored to use `client` directly instead.

### PR DESCRIPTION
**Pull request by Nydauron**
Closes #35.

Implements the solution provided by #35 and propagates the change to all the affected functions

### CODE REVIEW

**Comment by Nydauron** [comment]
Bro forgot the login token for CI

**Comment by AydanPirani** [comment]
@Nydauron  Thanks for the PR! For now, I might keep the database handler abstraction logic (just for portability purposes in case we extend to a different database), but will definitely steal your MongoClient idea and implement that

**Comment by Nydauron** [comment]
> just for portability purposes in case we extend to a different database

The reason why I just removed the `DatabaseHelper` class is bc imo it doesn't really achieve any beneficial abstraction. If, say, you were to change databases s.t. the query language is now, say Postgre, the abstract functions signatures in `DatabaseHelper` would all change, resulting in a full codebase refactor regardless.

I'll add my two cents here, but if you truly wanted an abstract helper class for databases, it's better to have something like this:

https://github.com/HackIllinois/api/blob/b2ef184b6ddbfc2a4fa3d88321237424ba8e5361/common/database/database.go#L13-L34

However, I still don't see if the gains from abstraction outweigh the costs with `DatabaseHelper` or in the code snippet I gave. You effectively lose ownership of the client instance once you wrap it in a derived class, and if you make an abstract base class, you have to then reimplement all fundamental features for all derivatives. If you say you had to manage multiple types of databases/keystores at runtime, I could see how an abstract class would be useful, but at this small scale, that doesn't seem like it would be the case.

To me, if you want a level of database abstraction, then ORMs are better than making your own abstract class.

Alright, rant done. Ty for looking at the PR.

**Review by AydanPirani — APPROVED** [review]
Approving and merging, might need to fix linter eventually

**Pull request merged**
